---

- name: Gather os specific variables
  import_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
  tags: vars

...
