---

- name: Create new machine-id of cloned VM
  block:
    - name: remove /etc/machine-id
      ansible.builtin.file:
        path: /etc/machine-id
        state: absent
    - name: remove /var/lib/dbus/machine-id
      ansible.builtin.file:
        path: /var/lib/dbus/machine-id
        state: absent
    - name: generate new machine-id
      ansible.builtin.shell: systemd-machine-id-setup

- name: Change hostname of cloned VM
  ansible.builtin.hostname:
    name: "{{ nameofhost }}.{{ nameofdomain }}"
    use: systemd

#- name: Change network address of cloned VM
#  community.general.nmcli:
#  - set_fact:
#      ip_addr: "{{ lookup('dig', '{{ item }}' ) }}"
#    with_items: "{{ inventory_hostname }}"
#    conn_name: "ens18"
#    ifname: "ens18"
#    type: "ethernet"
#    ip4: "{{ ip_addr }}/24"
#    gw4: "192.168.69.1"
#    state: present

...
